### ISSUE TITLE
Sofe assumes that ALL imports inside of a sofe service are relative urls

### ISSUE THREAD

**Issue by joeldenning** [CanopyTax/sofe#10]
See https://github.com/CanopyTax/sofe/blob/master/src/utils.js#L26. If a sofe service is not importing another sofe service, then it assumes it's a relative path.

This means that from inside a sofe service if you import something that uses a loader (such as a css file), it will not work even if you have that css loader installed locally (outside of the sofe service).

**Comment by joeldenning** [comment]
Credit to @lbntly for being brave enough to attempt to import a loader from inside of a sofe service.

**Comment by blittle** [comment]
So some edge cases really come up here. We should really clearly define the desired functionality on how imports work inside a service.

**Comment by joeldenning** [comment]
Here's my initial stab at how to determine where to load things from, when a sofe service is importing more things.
(1) If the sofe service is trying to import a sofe service, then by all means do so. See https://github.com/CanopyTax/sofe/blob/master/src/utils.js#L37 for where this is happening already
(2) If the name of the import starts with a `.` then assume that this is a relative path and resolve it like https://github.com/CanopyTax/sofe/blob/master/src/utils.js#L32
(3) Otherwise, we really have no idea what to do. Sofe should just be a pass through to whatever SystemJS defaults to. If you get lucky enough to have the write things installed in your app that brought in the sofe service, then it might work out okay. But the more likely scenario is that the whole world dies. But that's the best we can do I think.

What are your thoughts @blittle ?

**Comment by blittle** [comment]
@joeldenning I like it. What if a dependency starts with a `/` instead of a `.`?
