### ISSUE TITLE
Move off of `System.sofe`, towards `System.getConfig().sofe`

### ISSUE THREAD

**Issue by joeldenning** [CanopyTax/sofe#32]
See https://github.com/systemjs/systemjs/issues/999 and https://github.com/CanopyTax/sofe/blob/master/src/sofe.js#L5. This cannot be done until the systemjs issue is decided on and implemented. Also, as part of this, it might be a good idea to always call System.getConfig(), instead of just calling it once.

**Comment by blittle** [comment]
@joeldenning it seems like our usage is still okay? See the release notes for https://github.com/systemjs/systemjs/releases/tag/0.20.3

Also `System.getConfig().sofe` is undefined in SystemJS v0.20.12`

**Comment by joeldenning** [comment]
👍
