### ISSUE TITLE
SystemJS 2.0 compatibility

### ISSUE THREAD

**Issue by filoxo** [CanopyTax/sofe#44]
I recall that there was some discussion about problems with SystemJS 2 and sofe, but I can't for the life of me remember what they were. What known problems or limitations are there? Mainly asking for some visibility and so I can point people to this issue.

**Comment by joeldenning** [comment]
Sofe is a plugin for SystemJS@<1, but the plugins api for SystemJS@2 is completely different.

Old plugins api: https://github.com/systemjs/systemjs/blob/0.21/docs/creating-plugins.md
New plugins api: https://github.com/systemjs/systemjs/blob/master/docs/hooks.md

I have it on my to-do list to migrate Canopy to SystemJS@2.0, including upgrading sofe. I even talked about it with Justin and  Anthony last week. But I'm not sure exactly when I'll get to it.

**Comment by joeldenning** [comment]
Sofe is no longer necessary with systemjs@2 and systemjs@3, because [import maps]() do much the same thing. I think we should update the documentation of sofe to say that it is now preferred to use systemjs@3 and import maps.

**Comment by joeldenning** [comment]
See #45
