### ISSUE TITLE
Make sofe isomorphic

### ISSUE THREAD

**Issue by joeldenning** [CanopyTax/sofe#7]
What are your thoughts?

**Comment by blittle** [comment]
My initial impression is no, not needed cause back-end services are a different concept, sofe is for the browser. That said, with universal apps, the code can be rendered on the server or in the browser. If some of your rendering requires a service, then in order for sofe to support universal js apps it would  need to run on the server too. 

Do you know how well System.js supports non browser environments?

**Comment by joeldenning** [comment]
SystemJS [is isomorphic](https://github.com/systemjs/systemjs#nodejs). I think the only things that make sofe not isomorphic write now is when we write to the window and when we use <a> elements to parse urls.
